# This workflow will do a clean installation of python and module requirements, build the source code and add the exe file in the respective release
name: Build and Deploy on Release

on:
  release:
    types: [published]

run-name: Release ${{ github.event.release.tag_name }}
jobs:
  build:
    runs-on: windows-latest
    steps:

      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Run pyinstaller
        run: pyinstaller --clean --icon=app.ico -F -n "${{ github.event.release.tag_name }}" main.py

      - name: Upload file
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "dist/${{ github.event.release.tag_name }}.exe"
          overwrite: true
          draft: false
          tag_name: ${{ github.event.release.tag_name }}